### ISSUE TITLE
Ajaxing element with checkboxes does not init them.  Can't find documentation on how to manual init

### ISSUE THREAD

**Issue by rustinlewis** [creativetimofficial/material-dashboard#1]

**Comment by alexandru-paduraru** [comment]
@rustinlewis thank you for using our product. Material Dashboard was built over the Bootstrap Material Design made by Federico, I've checked and on his documentation, he recommends to user arrive.js for the elements that are added dynamically -> https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support.

Please let us know if that was helping you.

Best,
Alex

**Comment by rustinlewis** [comment]
Yep, that did the trick, thanks.
