### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by ruchern** [creativetimofficial/material-dashboard#10]
Are there plans for Bootstrap 4 support?

**Comment by alexandru-paduraru** [comment]
@ruchern thank you for your interest in our product. Yes, we will upgrade it to BS4 when there will be a stable version, at least a BS4 Beta. Please stay tuned, we will give more information when we have something. If you want to contribute for the migration we would be glad to made you a collaborator.

Best,
Alex

**Comment by ruchern** [comment]
Thank you @alexandru-paduraru
