### ISSUE TITLE
Navbar submenu does not work

### ISSUE THREAD

**Issue by praveenagunasekera** [creativetimofficial/material-dashboard#104]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ *] I am running the latest version
- [* ] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed
- [ *] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Want to have a multi level drop down in the nabar.

# Current Behavior

I have used the class submenu as mentioned in bootstrap 4 documentation. But no luck!

**Comment by groovemen** [comment]
Hello @praveenagunasekera 

Thank you for using our products, I will ask you to send us your orderID to make some verification. 

All the best, 
Stefan

**Comment by tbjbu2** [comment]
Having this issue too.

**Comment by groovemen** [comment]
Hello guys, 

Thank you for your interest in working with our products, please let us know about what product are you using because the multi-level dropdown is a PRO feature. 

Best, 
Stefan

**Comment by praveenagunasekera** [comment]
Hi Stefan,

Thankyou for the email. I am developing a website using material-dashboard for the use of inventory management for my personal business. How can I be able to use the multi-level dropdown as I’m still unable to use it.

Regards,
Praveena.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by groovemen** [comment]
You will be able to use multi-level dropdown by using this product: https://www.creative-tim.com/product/material-dashboard-pro (the PRO version)
Best, 
Stefan
