### ISSUE TITLE
npm run build is too slow when coupled with Azure Git with Azure pipelines on Azure Cloud, Build is not realistic

### ISSUE THREAD

**Issue by haloabove** [creativetimofficial/material-dashboard#108]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by websforestinc** [comment]
ok i will check

**Comment by websforestinc** [comment]
Freelancer (https://www.freelancer.com/)

Muhammad has given you $20 USD to try Freelancer!

Freelancer.com gives you access to millions of freelancers from all around the world. Simply answer a few quick questions to post a project, and receive free quotes from freelancers in just a few minutes.

Claim Your $20 → (https://www.freelancer.com/get?id=41708100&source=gge)

* Credit available when you have verified your payment method.

What can you get done on Freelancer?

Graphic Design (https://www.freelancer.com/graphic-designers)
Website Development (https://www.freelancer.com/website-developers)
Translation (https://www.freelancer.com/translators)

Marketing (https://www.freelancer.com/internet-marketing)
Mobile Development (https://www.freelancer.com/mobile-app-development)
Photography (https://www.freelancer.com/local/photography)

© 2020 Freelancer Technology Pty Limited. All Rights Reserved.
Level 20, 680 George Street, Sydney, NSW 2000, Australia

Privacy Policy (https://www.freelancer.com/page.php?p=info%2Fprivacy) | Terms and Conditions (https://www.freelancer.com/page.php?p=info%2Fterms) | Unsubscribe (https://www.freelancer.com/users/email/subscriptions.php?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkZyZWVsYW5jZXJcXEdBRlxcQ29yZVxcSldUXFxKV1QifQ.eyJpZCI6bnVsbCwic3ViIjoidW5zdWJzY3JpYmUiLCJpYXQiOjE1ODM2MTI3NDN9.RhdHxTe335xt7AAg6DHXRzlUyw_HohKg47uICiDWQSA) | Get Support (https://www.freelancer.com/support) | Get Free Credit (https://www.freelancer.com/give?from=email_footer)

Facebook (https://www.facebook.com/fansoffreelancer) Twitter (https://twitter.com/freelancer) Instagram (https://www.instagram.com/freelancerofficial)

Download our mobile app (https://bnc.lt/edm-download-freelancer)

(https://bnc.lt/edm-download-freelancer)
