### ISSUE TITLE
Perfect scrollbar error results in blank page

### ISSUE THREAD

**Issue by Flobbos** [creativetimofficial/material-dashboard#109]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [NO] I am running the latest version
- [YES] I checked the documentation and found no answer
- [NO] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I am expecting the page to not be blank in windows

# Current Behavior

Page is blank in windows

# Failure Information (for bugs)

Uncaught TypeError: $(....).perfectScrollbar is not a function

## Steps to Reproduce

Use Windows. 

This doesn't come up on Mac, naturally, but I have to manually go in and disable perfectScrollbar in material-dashboard.js starting on line 18, where I just set isWindows to false so it won't trigger the stupid scrollbar thing. Can this be fixed at some point in time? It's been going on for well over a year now.

**Comment by groovemen** [comment]
Hello @Flobbos,

Thank you for using our products, we will prepare an update for this product and we will fix this issue immediately. Sorry for this inconvenience.

All the best, 
Stefan
