### ISSUE TITLE
npm install WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

### ISSUE THREAD

**Issue by aefika** [creativetimofficial/material-dashboard#111]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes, Material Dashboard Pro - v2.1.0 ] I am running the latest version
- [ No ] I checked the documentation and found no answer
- [ Yes ] I checked to make sure that this issue has not already been filed
- [ Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
On npm install, I'm expecting no warnings for deprecated:
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
Please provide instructions to upgrade

# Current Behavior

What is the current behavior?
npm WARN deprecated popper.js@1.16.1

**Comment by yorvinlunawisky** [comment]
I´m having the same issue. Have you fixed it?

**Comment by aefika** [comment]
I haven't touched it. It seems that this upgrade requires several modifications in CSS and methods. I guess that's why CreativeTim has not answered. https://popper.js.org/docs/v2/migration-guide/

Also, heads-up for several packages included in \public\material\js\plugins, they are outdated but working. I've updated manually several of them to be sure to be up to date: moment (also included the locales), sweet alert, chartist and bootstrap-switch. The rest is probably outdated but not using them personally.

**Comment by yorvinlunawisky** [comment]
This is very strange. 30 minutes ago I sent the repo to a friend, he cloned it and everything went ok. He didn´t touch anything but for some reason it worked. Anyway if I find the answer I will let you know and thanks for the info above.

**Comment by yorvinlunawisky** [comment]
@aefika I "find" the solution. Seems that npm is not as good as yarn in poor connections. So I'm not sure how good is your internet but just in case, try using yarn instead of npm.
