### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by SalmenDev** [creativetimofficial/material-dashboard#116]
Hello, 
I'm using material dashboard, and i am trying to create a login page using the div Card, however i am unable to add a background image to the whole page  and the transparent aspect to the card-body.
The first Image will show what i managed to create, and the second one is what i want it to look like.

Thank you
![Done](https://user-images.githubusercontent.com/58747999/76617076-c0bc9080-6525-11ea-97c7-f6a65ce44fb8.JPG)
![ToDo](https://user-images.githubusercontent.com/58747999/76617093-cc0fbc00-6525-11ea-88e2-1386ae797e86.JPG)

**Comment by GCPBigData** [comment]
Angular Project ?
