### ISSUE TITLE
Checkbox design

### ISSUE THREAD

**Issue by twinkle-24** [creativetimofficial/material-dashboard#119]
I want to increase the size of checkmark for 4k screen couldn't do it. need help.

**Comment by groovemen** [comment]
Hello @twinkle-24,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
