### ISSUE TITLE
SASS Error. Failed to Compile! 

### ISSUE THREAD

**Issue by Dsabillon** [creativetimofficial/material-dashboard#120]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I´m looking for the first render but i can´t. 

# Current Behavior

Failed to Compile. 
./src/assets/scss/argon-dashboard-react.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/argon-dashboard-react.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
Require stack:
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\sass-loader\dist\getDefaultSassImplementation.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\sass-loader\dist\getSassImplementation.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\sass-loader\dist\index.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\sass-loader\dist\cjs.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\webpack\lib\NormalModule.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\webpack\lib\Compiler.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\webpack\lib\webpack.js
- C:\Users\dsabi\Downloads\argon-dashboard-react-master\argon-dashboard-react-master\node_modules\react-scripts\scripts\start.js

**Comment by groovemen** [comment]
Hello @Dsabillon,

Thank you for using our products, it looks like you opened an issue on the wrong repo. 
Please make sure you are opening it on the product repo. 
Best, 
Stefan

**Comment by Dsabillon** [comment]
Hello @groovemen 


I think this is the right place.

I found your products online, and I'm trying to use your Dashboard components to create one. But at the moment of starting the project, it gives me that error.

**Comment by groovemen** [comment]
Hello again, 

Please let us know if you are using Argon Dashboard React or Material Dashboard HTML. 

Regards, 
Stefan

**Comment by Dsabillon** [comment]
Hi
Thanks for take time for reply my question.

I´m using this :
https://www.creative-tim.com/product/material-dashboard-react

I´ve trying to figure out how use the components!

**Comment by EINazare** [comment]
Hello there, @Dsabillon ,

You have opened the issue on the wrong repository.
Please use the following form for us to understand your issue: https://www.creative-tim.com/new-issue/material-dashboard-react

Since the issue was opened wrongfully, we will close it here and we'll wait for the proper one to be opened.

Best,
Manu
