### ISSUE TITLE
[Bug] Vertical resize for textareas

### ISSUE THREAD

**Issue by rgonzalez-gnt** [creativetimofficial/material-dashboard#140]
### Version
2.1.2
### Reproduction link
https://jsfiddle.net/Lojqd417/
### Operating System
Linux
### Device
VMware
### Browser & Version
Firefox 83
### Steps to reproduce
Having this code in a webpage:

 <fieldset>
      <legend><h4>Configuración:</h4></legend>
      <div class="form-group">
         <label for="RepositorioGeneralDirs_nombre" class="required">Nombre: <span class="required">*</span></label>         <input class="form-control" name="RepositorioGeneralDirs[nombre]" id="RepositorioGeneralDirs_nombre" type="text" maxlength="255" value="" />         <div class="clsErrorMessage" id="RepositorioGeneralDirs_nombre_em_" style="display:none"></div>      </div>
      <div class="form-group">
         <label for="RepositorioGeneralDirs_descripcion">Descripción:</label>         <textarea class="form-control" name="RepositorioGeneralDirs[descripcion]" id="RepositorioGeneralDirs_descripcion"></textarea>         <div class="clsErrorMessage" id="RepositorioGeneralDirs_descripcion_em_" style="display:none"></div>      </div>
   </fieldset>

And this CSS overriding textarea setting:

textarea {
   resize: vertical!important;
}

### What is expected?
The textarea should be resized with the mouse.
### What is actually happening?
Texarea is not resized

---
### Additional comments
In the jsfiddle it works, because the material dashboard css is not included.

**Comment by groovemen** [comment]
Hello @rgonzalez-gnt,

Thank you for using our products, to vertically resize a **textarea** element, you can use the CSS **resize** property. 

```
textarea {
  resize: vertical;
}
```

You can also set the resize property to both if you want the user to be able to resize the **textarea** both **vertically** and **horizontally**. Here's an example:
```

textarea {
  resize: both;
}
```
Keep in mind that the resize property does not work on all browsers and may not be supported on older versions of some browsers.
All the best,
Stefan
