### ISSUE TITLE
sidebar localization

### ISSUE THREAD

**Issue by dewelloper** [creativetimofficial/material-dashboard#16]
i want to use 18n internationalization in the pro template and also i think to localize the sidebar with a manner
is there any solution or opinion about?

thanks!

**Comment by alexandru-paduraru** [comment]
@dewelloper thank you for using our product. I think you need to customize the internationalization at the Backend level, not the front end where is the dashboard. Inside the dashboard you will have something like this `<a href="#link">internationalization[your_word]</a>`. Then everything inside that vector will come from the backend. This is how I think this is working. 

Here are more details about how you can achieve that using PHP: https://lingohub.com/blog/2013/06/php-internationalization-i18n-mechanisms-tutorial/

Please let us know if that was helpful.

Best,
Alex

**Comment by dewelloper** [comment]
Thank you Alex for the urgent reply.
In my projects status i have to implement the front end layer with angular2 ( i18n). I dont think to use backend localization that is not a solution for my case.
Just my question about menu localization: it have to be dynamic and localized according last user ip-location becouse it will be a global site, 
i will try to solve thank you

**Comment by alexandru-paduraru** [comment]
@dewelloper now I understand, I didn't understand from the first comment that you are using Angular 2 :D 

We have an Angular 2 version for [MD Free](https://github.com/creativetimofficial/material-dashboard-angular) and also for the [MD PRO Angular2](http://md-pro-angular2.creative-tim.com/), but they don't have the i18n part included. We've seen requests for the internationalization after we launched the products so at this moment we are doing research to see how to integrate it in the Angular 2. 

What we found till now are these sources

- http://stackoverflow.com/questions/34797512/angular2-i18n-at-this-point
- https://angularjs.blogspot.ro/2016/09/angular-2-rc6_1.html
- https://github.com/StephenFluin/i18n-sample

To get the IP of the user and his country maybe this will help: http://stackoverflow.com/questions/3489460/how-to-get-visitors-location-i-e-country-using-javascript-geolocation

Hope this will help you. As soon as we have something official and stable we will include in the Angular projects too.

Best,
Alex
