### ISSUE TITLE
[Bug] Icons page not loading on live preview

### ISSUE THREAD

**Issue by lucas-marx** [creativetimofficial/material-dashboard#162]
### Version
live preview
### Reproduction link
https://demos.creative-tim.com/material-dashboard-dark-pro/examples/components/icons.html
### Operating System
linux mint 19.01
### Device
notebook
### Browser & Version
chrome  v88.0.4324.182
### Steps to reproduce
container with icons doesn't load, it says the connection was refused.
### What is expected?
show icons
### What is actually happening?
crashing

---

**Comment by groovemen** [comment]
Hello @lucas-marx,

Thank you for using our products and for letting us know about this issue. Until the next product update, please follow the following link: https://fonts.google.com/icons. 
Please let us know if we can help with any other details.

All the best,
Stefan
