### ISSUE TITLE
[Bug] Documentation layout broken

### ISSUE THREAD

**Issue by lucasssvaz** [creativetimofficial/material-dashboard#171]
### Version
2.1.2
### Reproduction link
https://demos.creative-tim.com/material-dashboard/docs/2.1/components/forms.html
### Operating System
Linux Mint 20.2 / Windows 10 Pro
### Device
Desktop / Mobile
### Browser & Version
Google Chrome 92.0.4515.131
### Steps to reproduce
1. Open the Material Dashboard documentation
2. Go to the 'Forms' section.
3. Scroll down through the section. You'll be able to see lots of formatting bugs and missing icons, including the page header bar.
### What is expected?
The examples to be shown properly, rendering the icons and at the correct position.
### What is actually happening?
Some elements are being rendered on top of each other, icons are not loading, elements such as <select> have the wrong size and checkboxes animations and icons are broken

---
### Solution
As this occurs on both Material Dashboard and Flask Material Dashboard, some CDN package might be broken. Updating the links should fix the issue.
### Additional comments
This happens on both Material Dashboard and Flask Material Dashboard documentations. It was tested on 2 computers (one running Linux and the other running Windows) and a mobile page (cleaning all cache) and the results were the same.

**Comment by groovemen** [comment]
Hello @lucasssvaz,

Thank you for using our products and for letting us know about this issue. Until the next product update where we fix this issue, please use the following [link](https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/components/forms.html). It's from the pro version of the products and it contains all you can find in the free version. 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
