### ISSUE TITLE
Incorrect checkbox and radiobutton styles on iOS (creative-tim.com example)

### ISSUE THREAD

**Issue by and7ey** [creativetimofficial/material-dashboard#18]
See images below.
Tested on different iOS devices (iPad 4, iPhone 5s, iPhone 6) and different browsers (Google Chrome-based).

![whatsapp image 2017-05-01 at 22 04 25](https://cloud.githubusercontent.com/assets/900474/25590960/3b5911b4-2ebb-11e7-8c95-a98cdc79b3e5.jpeg)
![whatsapp image 2017-05-01 at 22 04 19](https://cloud.githubusercontent.com/assets/900474/25590959/3b5834ec-2ebb-11e7-8b4b-60d10620a0b7.jpeg)

**Comment by dragosct10** [comment]
Hi @and7ey ! For fixing this issue please take the uploaded scss partials `_mixins.scss` and `_checkboxes.scss` and just replace them on project `assets/sass/md/_mixins.scss` and `assets/sass/md/_checkboxes.scss`. Please after that compile you're scss with [Koala](koala-app.com) and be sure the output path is `assets/css/material-dashboard.css`.


[_checkboxes.scss.zip](https://github.com/creativetimofficial/material-dashboard/files/975975/_checkboxes.scss.zip)
[_mixins.scss.zip](https://github.com/creativetimofficial/material-dashboard/files/975976/_mixins.scss.zip)

**Comment by and7ey** [comment]
Many thanks! There are also some problems with input fields on iOS - font color seems to be white (but when the field loses focus and get it again - it becomes black). Should I raise another issue?

**Comment by and7ey** [comment]
Looks like the patch didn't help. Here is the file I generated - https://pastebin.com/xa3HXmHa. I've cleared cash, but still radiobuttons and checkboxes displayed incorrectly. I test it on iPad 4, iOS 8.4 and latest Google Chrome and Safari there.

**Comment by dragosct10** [comment]
Hi @and7ey! I checked again the files and I made a few modifications. I will upload again the both files. Please follow the steps above that I wrote for you to achieve the replacement of the files. Hope that will help you!

[_checkboxes.scss.zip](https://github.com/creativetimofficial/material-dashboard/files/984126/_checkboxes.scss.zip)
[_mixins.scss.zip](https://github.com/creativetimofficial/material-dashboard/files/984127/_mixins.scss.zip)

Regards,
Dragos

**Comment by and7ey** [comment]
Thanks, Dragos. It fixed the display problem with checkbox (at least with disabled-checked checkbox - what I use), but radiobuttons are still displayed incorrectly.
