### ISSUE TITLE
[Feature Request] Material Dashboard 2 Laravel

### ISSUE THREAD

**Issue by Marion5** [creativetimofficial/material-dashboard#181]
I love Material Dashboard - will there be Material Dashboard 2 with Bootstrap 5 for Laravel?

**Comment by groovemen** [comment]
Hello @Marion5,

Thank you for your interest in working with our products, we will launch this product in the next couple weeks. 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
