### ISSUE TITLE
[Bug] Template does not work

### ISSUE THREAD

**Issue by francisjervis** [creativetimofficial/material-dashboard#197]
### Version
2.12
### Reproduction link
https://demos.creative-tim.com/material-dashboard/docs/2.1/getting-started/introduction.html
### Operating System
Mac
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
1: Download code from Github
2: Try to run minimal Flask app serving "basic template"
3: It does not work because the 
### What is expected?
The page is styled.
### What is actually happening?
The page is completely unstyled. No CSS whatsoever.

---
### Solution
Buy a different template

**Comment by groovemen** [comment]
Hello @francisjervis,

Thank you for using our products, to solve this issue, please add the `./`in front of all script paths. We'll fix it in the next product update.
All the best,
Stefan
