### ISSUE TITLE
Sidebar wrapper height calculation breaks when adding a taller logo

### ISSUE THREAD

**Issue by Frondor** [creativetimofficial/material-dashboard#20]
If you add an image, or create a multi line text... Any element which height is bigger than the actual "CREATIVE TIM" text, the wrapper is adding additional space towards the bottom of the page and sidebar "floats"...

~I fixed it by switching to `height: auto` or directly removing that line:~ (nvm, it doesnt fix the problem, because you can't scroll down on smaller screens, probably the best way is to set `overflow-y:hidden` for `body .wrapper`)
https://github.com/creativetimofficial/material-dashboard/blob/master/assets/css/material-dashboard.css#L445

**Comment by alexandru-paduraru** [comment]
@Frondor thank you for pointing that out. Yes, the best option would be to have the scroll on the `.sidebar` but then you will not have the brand visible. We made it like that because the users wanted to have the brand visible no matter if you scroll or not. Makes sense? :D 

Best,
Alex

**Comment by Frondor** [comment]
Not really, because all brands don't use the same height, and sidebar's height should be dynamic regardless the height of logos. I'm not talking about hiding anything, but preventing that "glitch" in this specific case

**Comment by alexandru-paduraru** [comment]
Got it. We will think of a way to do that and also to have it visible, not going with the scroll for the next update release. 

Thank you again for pointing out!

**Comment by Frondor** [comment]
We don't need any new scroll... `.sidebar-wrapper` is in charge of that and it does pretty well.

In case we are not getting each other :D 
![https://i.gyazo.com/56dd78c6259d5440c5a3d47951f43e56.gif](https://i.gyazo.com/56dd78c6259d5440c5a3d47951f43e56.gif)

*Note: this problem appears only on desktop screens, and I managed to fix it by removing the height calculation for `.side-bar` and setting `overflow-y: hidden` to `.wrapper`

**Comment by alexandru-paduraru** [comment]
Ok ok, now I got it :D a video is like 10.000 words. Yes, you're right with the solution. 

Best,
Alex
