### ISSUE TITLE
Sub-nav in Sidebar

### ISSUE THREAD

**Issue by 91Abdullah** [creativetimofficial/material-dashboard#21]
Hi,

Thanks for the lovely HTML template. 

How can I add sub-menu in sidebar nav?

**Comment by alexandru-paduraru** [comment]
@91Abdullah thank you for using our product. You have 2 options:

1. Manually integrate and create the CSS style using the Bootstrap Collapse elements: http://getbootstrap.com/javascript/#collapse
2. Get the [Material Dashboard PRO](http://demos.creative-tim.com/material-dashboard-pro/examples/components/buttons.html) which already have that created for you.

Best,
Alex

**Comment by AltRoot17** [comment]
@91Abdullah   I faced the same issue . Did you got a any solution

**Comment by 91Abdullah** [comment]
> @91Abdullah I faced the same issue . Did you got a any solution

@AltRoot17 I applied solution given by Alex.

I manually integrated bootstrap collapse.

I suggest you to apply same.

http://getbootstrap.com/javascript/#collapse

**Comment by AltRoot17** [comment]
Thanks I'll Try it
