### ISSUE TITLE
[Bug] Notification dropdown box-shadow

### ISSUE THREAD

**Issue by abhishekrawat22** [creativetimofficial/material-dashboard#217]
### Version
2
### Reproduction link
https://demos.creative-tim.com/material-dashboard/pages/dashboard.html?ref=readme-md2
### Operating System
Windows
### Device
Acer Nitro 5
### Browser & Version
Chrome(114), Firefox(114), Edge(114)
### Steps to reproduce
1. Open the mentioned link.
2. Click the bell icon in the navbar header.
3. Adjust the device width in the responsive mode below 992px.
### What is expected?
Box-shadow should be there to create a layer of separation from the same white-colored background cards.
### What is actually happening?
As the dropdown and the dashboard card's backgrounds are the same. It is getting difficult to know the separation and where the dropdown box ends.

---
### Solution
Remove the **box-shadow: none!important;** given after **@media (max-width: 991.98px)** media query to the **.navbar .navbar-collapse .navbar-nav .dropdown .dropdown-menu** selector.

**Comment by groovemen** [comment]
Hello @abhishekrawat22,

Thank you for your solution in fixing this issue. We will integrate it into the next product update. 
Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by abhishekrawat22** [comment]
Sure, thank you.

**Comment by abhishekrawat22** [comment]
Hi @groovemen 

May I know when are you planning to launch the next update and can I create a PR for the solution?
