### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by bennyAG** [creativetimofficial/material-dashboard#22]
It doesnt seem to include pagination can i include Tim material kit to have that or will it cause classes to be loaded twice? I am asking actually why wasn't Tim material kit loaded separately ?

**Comment by alexandru-paduraru** [comment]
@bennyAG thank you for using our product. Yes, it will be loaded twice. We added the pagination in the [PRO version](http://demos.creative-tim.com/material-dashboard-pro/examples/components/buttons.html) but you can also add it manually following this tutorial:

We recommend you to get just the SASS file for the pagination from `mk/assets/sass/mk/_pagination.scss` and move it to `md/assets/sass/md/...` then add it also in `md/assets/sass/material-dashboard.scss` like how it is added in `mk/assets/sass/material-kit.scss` and compile the `material-dashboard.scss` using [Koala](http://koala-app.com/). Make sure you set the output path to css/material-dashboard.css in koala.

Let us know if that was working fine for you.
