### ISSUE TITLE
Issue with keyframe in media query

### ISSUE THREAD

**Issue by danjohnso** [creativetimofficial/material-dashboard#23]
Giving the base version a look through before I purchase pro, I noticed that the responsive.scss file contains a keyframe definition for fadeIn which is located inside a media query.  IE 10-11 won't respect it and the animation will never work, and having it inside the media query causes errors in csslint and when trying to minify the file.  Moving the keyframe definitions outside the media query fixes both issues.

Also odd, this one animation is defined in responsive.scss, while all of the others are in animate.scss including the reciprocal fadeInDown, is this intentional?

**Comment by alexandru-paduraru** [comment]
@danjohnso thank you for your interest in our product. We've checked and there is no constraint for keeping the fadeIn animation inside the Media Query, you can move it outside of it without any problems.

Best,
Alex
