### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by OgreTransporter** [creativetimofficial/material-dashboard#26]
The sidebar color filter is a nice function. Is it possible to extend the function to change the primary color of the whole page? It doesn't make sense to change only the primary color of the sidebar.

**Comment by alexandru-paduraru** [comment]
@OgreTransporter thank you for the suggestion. We used that just for demo purpose, you can change the color of the primary for the whole dashboard just by changing a variable in SASS, more details are in the documentation of the product: http://demos.creative-tim.com/material-dashboard/documentation/tutorial-components.html#changing-colors

We will see in the next updates if we will do that.

Best,
Alex

**Comment by seferdemir** [comment]
Page not found!
