### ISSUE TITLE
Ignores brand-primary with new color swatch to _colors.scss

### ISSUE THREAD

**Issue by simonl65** [creativetimofficial/material-dashboard#27]
So I've added a new color swatch to _color.scss ($newcolors) that has all the color-ways of existing swatch (e.g. $newcolors-50 to -A700 and $newcolors: $newcolors-500 !default;). I then changed _variables.scss to $brand-primary: $newcolors !default; but now I don't get the background color for the active item in the sidebar - what am I missing?

Edit: I also changed data-color="newcolors" in the sidebar div.

Cheers,
Simon

**Comment by alexandru-paduraru** [comment]
@simonl65 please make sure you create the group of CSS properties for `data-color="newcolors"` too as they are created in `sass/_sidebar-and-main-panel.scss` line 190

```css
&[data-color="blue"]{
        @include set-background-color-button($brand-info);
    }
```

Best, 
Alex

**Comment by simonl65** [comment]
@alexandru-paduraru Many thanks for that. I'm busy with something else at the mo' but will try it a.s.a.p. 👍
