### ISSUE TITLE
Column Offset Not Working - Bootstrap 3

### ISSUE THREAD

**Issue by yashviJ993** [creativetimofficial/material-dashboard#28]
**Using Bootstrap 3**

I have included the required files and maintained the file structure. However, Column Offset classes are not supported.

I also, checked on:
https://github.com/FezVrasta/bootstrap-material-design

The offset works when I just use the material kit files.

**Comment by alexandru-paduraru** [comment]
@yashviJ993 thank you for using our product. Please check the next image showing the column offset working fine:

<img width="823" alt="screen shot 2017-07-08 at 17 40 17" src="https://user-images.githubusercontent.com/2517758/27986198-a834c50c-6404-11e7-9928-df77ba169bd9.png">

More about cols offset can be found in the original documentation of bootstrap: http://getbootstrap.com/css/#grid-offsetting

Hope this helps.

Best,
Alex
