### ISSUE TITLE
Fixed positioning not working

### ISSUE THREAD

**Issue by yudori** [creativetimofficial/material-dashboard#34]
I tried creating a floating action button as is conventional in material design but fixed positioning doesn't not work. The button scrolls along with the rest of the page instead of maintaining a position at the bottom right corner of the screen. When I take off the material-dashboard css file, it works. Here's my code:

`<a class="btn-floating><i class="material-icons">add</i></a>`

css:
```
a.btn-floating{
     position:fixed !important;
     right:20px;
     bottom:20px;
     padding:0;
     margin:0;
     z-index: 1;
}
```

PS: Awesome library you have here, Great work!

**Comment by alexandru-paduraru** [comment]
@yudori thank you for using our product. Please make sure you add the btn-floating outside of the `div.main-panel` and then everything will work fine.

Best,
Alex
