### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by irvingv8** [creativetimofficial/material-dashboard#37]
I think the way the brand-primary color is being implemented right now can be somewhat misleading, as it's based on the components having the data-color set to purple. So, changing the primary color to light-blue and having the data-color set to purple... I suggest setting a the data-color across the project pointing to something like: 'primary' so it can be easier to understand.

Also, this is about the angular material dashboard, all the data-colors for the primary color has been set to "red" so, changing the variable in line 28 of _colors has no effect.

**Comment by irvingv8** [comment]
also @alexandru-paduraru, this is totally unrelated but I've been working on a React Version of this template, it's on my repo right now, it's totally functional at this point, I need to enhance the notification system a little bit to make it look exactly like the original template, but it's almost there, I'd like you to take a look and provide some feedback:

https://github.com/irvingv8/material-dashboard-react

`yarn install`
`yarn start`

and you can take a look at the site

**Comment by alexandru-paduraru** [comment]
@irvingv8 wow that's great! We will have a look on it and come back with some feedback. If you are looking to continue the development and offer support for it we would be glad to add it as our official Material Dashboard React. Is this something that is interesting for you? Best, Alex!

**Comment by irvingv8** [comment]
@alexandru-paduraru tbh, that was the only purpose of that repo 😬, I wouldn't call it production ready just yet. But it'll be, eventually.
