### ISSUE TITLE
First tab shows ALL Tabs

### ISSUE THREAD

**Issue by eDigirolamo** [creativetimofficial/material-dashboard#39]
Using tabs to display a graph, I have 2 manufacturing plants and am trying to show a chart for each plant, The first tab shows All data, the second and third are plant specific. By all data I mean a chart that has cumulative data not show 3 charts.

On page load the default tab shows all three charts. If I click on another tab it shows only the specific chart(the correct way) 
Correct sshot
![screen shot 2017-09-28 at 8 56 08 am](https://user-images.githubusercontent.com/9492036/30967711-13c30b4c-a42b-11e7-979a-f51af62d192a.png)

Problem SShot
![screen shot 2017-09-28 at 8 55 38 am](https://user-images.githubusercontent.com/9492036/30967700-0a8f38fc-a42b-11e7-8ee1-26708b002cc8.png)

**Comment by KrunalSM** [comment]
Remove `active` from class
`<div class="tab-pane active" id="###">`
to
`<div class="tab-pane" id="###">`
in other tabs

**Comment by eDigirolamo** [comment]
Thanks @KrunalSM your a gentleman and a scholar, However this did fix my issue but brought another to light in regards to chart.js and having different charts on different tabs. Only the first tab charts render.  

Link to solution: [https://stackoverflow.com/questions/29861670/bootstrap-3-tabs-chart-js-charts-not-loading-on-tabs/46571601#46571601](url)
