### ISSUE TITLE
Will only print one page even on longer content

### ISSUE THREAD

**Issue by desert** [creativetimofficial/material-dashboard#46]
I detected this code, which prevents correct printing of long tables, texts or whatever
```
.main-panel {
  max-height: 100%;
  height: 100%;
}
```
I really don't know exactly if it's really needed but removing it allowed for printing multipage documents on Chrome.

BTW I just removed it and it still seems to render correctly.

**Comment by desert** [comment]
A different approach to print would be to override when printing using custom CSS 
```
@media print {
        .main-panel {          
          max-height: unset;
          height: unset;
        }
}
```

**Comment by humbertowoody** [comment]
Have you experienced any issues running without the `main-panel`class? I'm having the same issue and thinking about going live without it.
