### ISSUE TITLE
Demo download fails - 

### ISSUE THREAD

**Issue by shoqvalue** [creativetimofficial/material-dashboard#48]

**Comment by shoqvalue** [comment]
Tried to demoload demo of material dash pro.  Pissed off to find that it wouldn't even install, because you left out the style.css.  I'd like to buy this product, but now until I can see it. Hope you fix this soon
![2017-12-26_18h56_30](https://user-images.githubusercontent.com/10272750/34366805-20eec6d2-ea6f-11e7-89ad-6a06c8dfd6db.png)

**Comment by shoqvalue** [comment]
This was where I downloaded Demo from
https://www.creative-tim.com/product/material-dashboard?tracking=first-time#

**Comment by alexandru-paduraru** [comment]
Hi @shoqvalue thank you for your interest in working with our product. This is not a WordPress theme so you cannot install it in Wordpress. It is a plain HTML/Bootstrap template, that means you need to manually code it on your Wordpress if you want. Maybe this tutorial helps you: https://www.youtube.com/watch?v=nvsK0cTH0So

Best,
Alex
