### ISSUE TITLE
Sketch UI KIT

### ISSUE THREAD

**Issue by michailkouroupakis** [creativetimofficial/material-dashboard#5]
Hello where can i find a sketch UI kit with components nested symbols etc 
for this Material Dashboard ?

Thanks for your time
Michail

**Comment by alexandru-paduraru** [comment]
@michailkouroupakis thank you for your interest in our product. At this moment we don't have a Sketch version of Material Dashboard. We are working on it and it will be released soon. What we can offer you is the Sketch version of [Material Kit](http://www.creative-tim.com/product/material-kit)(most of the components, like buttons, tables are there) which can be found here: http://www.pixelsvibe.com/product/material-kit 

Best,
Alex

**Comment by BenAhlander** [comment]
This would be great!
