### ISSUE TITLE
Material-dashboard and Asp.Net MVC 5 in one application

### ISSUE THREAD

**Issue by slavo3** [creativetimofficial/material-dashboard#50]
Hi, i try to run this material-dashboard angular app in Asp.Net MVC 5 and i have error:

core.es5.js:1020 ERROR ReferenceError: $ is not defined
    at HomeComponent.Array.concat.HomeComponent.ngOnInit (home.component.ts:19)
    at checkAndUpdateDirectiveInline (core.es5.js:10843)
    at checkAndUpdateNodeInline (core.es5.js:12341)
    at checkAndUpdateNode (core.es5.js:12284)
    at prodCheckAndUpdateNode (core.es5.js:12974)
    at Object.eval [as updateDirectives] (HomeComponent_Host.ngfactory.js:9)
    at Object.updateDirectives (core.es5.js:12718)
    at checkAndUpdateView (core.es5.js:12251)
    at callViewAction (core.es5.js:12599)
    at execEmbeddedViewsAction (core.es5.js:12557)

home.components.ts (19 line):
 ngOnInit() {
    $.getScript('../../../assets/js/material-dashboard.js');
    $.getScript('../../../assets/js/initMenu.js');
  }

If i run this app with 'ng serve' (without mvc app), it builds the application and starts a web server and everythink is ok.

But if i try to do it following steps:
1.)ng build
2.)move directory 'dist' to my mvc app (target operation of copy : MyMvcWeb\Scripts\NgApp )

My view in mvc app:

@{
    Layout = null;
}
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Test app</title>
	<base href="/">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
	<app-root>Loading..</app-root>
	<script type="text/javascript" src="~/Scripts/NgApp/inline.bundle.js"></script>
	<script type="text/javascript" src="~/Scripts/NgApp/polyfills.bundle.js"></script>
	<script type="text/javascript" src="~/Scripts/NgApp/styles.bundle.js"></script>
	<script type="text/javascript" src="~/Scripts/NgApp/vendor.bundle.js"></script>
	<script type="text/javascript" src="~/Scripts/NgApp/main.bundle.js"></script>
</body>
</html>

Anyone knows what is wrong, what i have to do more or what is the problem?

**Comment by giansalex** [comment]
jquery?

**Comment by dragosct10** [comment]
Hi, @giansalex! I think you don't have the jquery because that $ sign is not defined it refers that jquery is missing. Regards, Dragos

**Comment by giansalex** [comment]
Hi @dragosct10 , i think the same, but the user is @slavo3

**Comment by slavo3** [comment]
Hi, thanks for responses. You're probably right, but I have changed the design version and I have no way to verify the hints.

**Comment by dragosct10** [comment]
Hi! Yes, @giansalex sorry for that. @slavo3 please, see this [tutorial](https://www.youtube.com/watch?v=Mi_SddLvU80). Regards, Dragos
