### ISSUE TITLE
How can i add new fonts to the project

### ISSUE THREAD

**Issue by omidgharib** [creativetimofficial/material-dashboard#51]
I add @font-face into material-dashboard-react.css but after compiling my urls changed to sth else what should i do?

**Comment by dragosct10** [comment]
Hi, @omidgharib! Please, open the issue on the react github repo of this product becaause in this way you will be helped more quicly. 

https://github.com/creativetimofficial/material-dashboard-react

Regards,
Dragos

**Comment by omidgharib** [comment]
Thank you so much i did it
