### ISSUE TITLE
.main-panel .content height wrongly calculated

### ISSUE THREAD

**Issue by stephankaag** [creativetimofficial/material-dashboard#52]
This element has a height of: `min-height: calc(100vh - 123px);`. This is too big and results in vertical scrollbars when there is little content on the page.

Where does this `123px` come from? Imho it should be something like `152px` to prevent the scrollbar.

**Comment by dragosct10** [comment]
Hi, @stephankaag! Thank you for using our products. You can adjust the height of the main-panel like you want, it's not a problem. Regards, Dragos
