### ISSUE TITLE
Unable to compile CSS for another color

### ISSUE THREAD

**Issue by ReddySk** [creativetimofficial/material-dashboard#54]
Hello, 

I have tried to recompile CSS with color red. 

I have updated sass/md/_variables at line 28 to `$brand-primary: $red !default;`

Then corrected paths in material-dashboard.scss because downloaded package has path sass/md/_* instead of _scss/md/*. 

But Koala says:
`"Error: Invalid CSS after \".../md/_variables\"\": expected \"{\", was \";\"\A         on line 23 of E:\Kamu\WEBy\themes\material-dashboard-v1.2.0\assets\sass\material-dashboard.scss\A \A 18: \A 19:  */\A 20: \A 21: \A 22: //variables and mixins\A 23: @import \"../sass/md/_variables\";\A 24: @import \"../sass/md/_mixins\";\A 25: @import \"../sass/md/_shadows\";\A 26: \A 27: //plugin css\A 28: @import \"../sass/md/plugins/_plugin-nouislider\";"; }`

Can you please advise what I am doing wrong? 

Thank you, 
Cheers, Reddy

Original and updated scss files:
[sass.scss.zip](https://github.com/creativetimofficial/material-dashboard/files/1834104/sass.scss.zip)

**Comment by dragosct10** [comment]
Hi, @ReddySk! Thank you for using our product. I noticed that you have the lines from below at the begin of the scss file, please remove it and try again to compile. 
---
# Front matter comment to ensure Jekyll properly reads file.
---

Regads, 
Dragos

**Comment by ReddySk** [comment]
Hello,

yes this helps! Thank you,

Cheers, Rudo

2018-03-22 9:54 GMT+01:00 dragosct <notifications@github.com>:
