### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by giansalex** [creativetimofficial/material-dashboard#56]
In main image says Bootstrap 4 but in source code uses v3. 3.7

**Comment by dragosct10** [comment]
Hi, @giansalex! Thank you for using our product. Please, can you show us exactly? Regards, Dragos

**Comment by giansalex** [comment]
![image](https://user-images.githubusercontent.com/14926587/38813090-af5e9614-4153-11e8-99f4-6374ed2db527.png)

**Comment by dragosct10** [comment]
Hi, @giansalex! Please download the BS4 version from this [link](https://www.creative-tim.com/product/material-dashboard). We are sorry for this inconvenience we will fix this issue. Thank you for your observation. 

Regards, 
Dragos

**Comment by giansalex** [comment]
thanks
