### ISSUE TITLE
Something is wrong with the demo 

### ISSUE THREAD

**Issue by ngkarkeong** [creativetimofficial/material-dashboard#58]
when you load the demo, you will get this error.

material-dashboard.min.js?v=2.0.0:35 
Uncaught TypeError: $(...).perfectScrollbar is not a function
 at material-dashboard.min.js?v=2.0.0:35

**Comment by groovemen** [comment]
Hello @ngkarkeong, thank you for using our products, we fixed this issue in the last version (**2.1.0**) of the product. 

Best, 
Stefan
