### ISSUE TITLE
form problem

### ISSUE THREAD

**Issue by Alanvome** [creativetimofficial/material-dashboard#59]
Here is a capture of the problem, but you can clearly see that the label of the form is on top of the input ... 
I am on latest version of Safari on MacBook Pro 2015...

Any Idea ?
<img width="813" alt="image" src="https://user-images.githubusercontent.com/36159540/40892255-cdecc062-6794-11e8-9d27-6452ac286020.png">
![image](https://user-images.githubusercontent.com/36159540/40892256-ce0e3d6e-6794-11e8-9c46-7c1c5bf3e97f.jpeg)

**Comment by groovemen** [comment]
Hello @Alanvome, thank you for using our products, please update your project to the latest version of the product where we fixed this issues. Also, check [documentation](https://demos.creative-tim.com/material-dashboard/docs/2.0/getting-started/build-tools.html#using-input-labels-in-a-form) to see how to use the labels. 

All the best, Stefan
