### ISSUE TITLE
how to use input type as file

### ISSUE THREAD

**Issue by piyushgohel** [creativetimofficial/material-dashboard#6]
Hello,

Input type as file not working in this dashboard.Any idea about how to use input type as file.

**Comment by alexandru-paduraru** [comment]
Hi @piyushgohel thank you for using our product. We have example with the file input plugin here: http://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html and the default file input from the original Kit [Material Bootstrap Design](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) is looking like this:

```
<div class="form-group is-empty is-fileinput">
            <input type="file" id="inputFile4" multiple="">
            <div class="input-group">
              <input type="text" readonly="" class="form-control" placeholder="Placeholder w/file chooser...">
                <span class="input-group-btn input-group-sm">
                  <button type="button" class="btn btn-fab btn-fab-mini">
                    <i class="material-icons">attach_file</i>
                  </button>
                </span>
            </div>
 </div>
```

Hope this will help you. 

Best,
Alex

**Comment by Haritsinh** [comment]
@piyushgohel , @SwathipriyaRaja The solution is given by @groovemen , in another issue : [solution](https://github.com/creativetimofficial/ct-material-dashboard-pro/issues/197#issuecomment-431815009)

in it stefan stated that you have to add below `js` code in your js file, you can add it in your material-dashboard.js:

```
// FileInput
  $('.form-file-simple .inputFileVisible').click(function() {
    $(this).siblings('.inputFileHidden').trigger('click');
  });

  $('.form-file-simple .inputFileHidden').change(function() {
    var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
    $(this).siblings('.inputFileVisible').val(filename);
  });

  $('.form-file-multiple .inputFileVisible, .form-file-multiple .input-group-btn').click(function() {
    $(this).parent().parent().find('.inputFileHidden').trigger('click');
    $(this).parent().parent().addClass('is-focused');
  });

  $('.form-file-multiple .inputFileHidden').change(function() {
    var names = '';
    for (var i = 0; i < $(this).get(0).files.length; ++i) {
      if (i < $(this).get(0).files.length - 1) {
        names += $(this).get(0).files.item(i).name + ',';
      } else {
        names += $(this).get(0).files.item(i).name;
      }
    }
    $(this).siblings('.input-group').find('.inputFileVisible').val(names);
  });

  $('.form-file-multiple .btn').on('focus', function() {
    $(this).parent().siblings().trigger('focus');
  });

  $('.form-file-multiple .btn').on('focusout', function() {
    $(this).parent().siblings().trigger('focusout');
  });
```

After adding this js code you can use file input as displayed by @alexandru-paduraru and it will work as you want.

**Comment by Calixtrao** [comment]
input don't upload image.  How to solve this issue?

**Comment by AcidSlide** [comment]
> input don't upload image. How to solve this issue?

if you are just getting the filename on the upload, you need to add `enctype="multipart/form-data"`

i've added the script to my form and it works now and images are uploaded to the server (tested and validated)
