### ISSUE TITLE
Floating label overlaps with placeholder

### ISSUE THREAD

**Issue by dietersanty** [creativetimofficial/material-dashboard#60]
Hello, 

im having an issue where the label with class 'bmd-label-floating' overlaps with the placeholder the browser provides when i use a type of an input field. (like date)

i've tried many browsers (Opera, Chrome, Edge) and its always the same issue.

![image](https://user-images.githubusercontent.com/40023097/41089782-f229f3fe-6a42-11e8-82e5-f401ee03db72.png)

Can you help me ?

With regards
Dieter

**Comment by parkbsu** [comment]
I'm running into a similar problem. I have the following form element defined in my layout:

`
< div class="form-group" >
     < label class="bmd-label-floating" >Artifact name< /label >
     < input id="artifactName" name="artifactName" type="text" class="form-control artifactData" />
     < span class="bmd-help" >** Need to fill in the help text **< /span>
< /div >
`

Using jQuery, when I set the `text` property of that input, I see this:

![image](https://user-images.githubusercontent.com/31696947/41351263-d20beba4-6ee3-11e8-8f1c-5f649ddcb73d.png)

When I click on the field and select it, the "is-filled" class is added to the form element (with the exception of the textarea - it always reverts back to overlapping the content), however I cannot get that class added on the initial page/data load.

Thanks for the help and amazing set of templates!

**Comment by groovemen** [comment]
Hello @dietersanty , thank you for using our products, please update your project to the [latest version](https://www.creative-tim.com/product/material-dashboard) of the product where we fixed this issues. Also, check the [documentation](https://demos.creative-tim.com/material-dashboard/docs/2.0/getting-started/build-tools.html#using-input-labels-in-a-form) to see how to use the labels. 

All the best, Stefan
