### ISSUE TITLE
Wrong label alignment

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/material-dashboard#61]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

Labels are wrong. on Material Dashboard Pro HTML v 2.0.1

![image](https://user-images.githubusercontent.com/16140960/41182271-ece0c7be-6b42-11e8-9da1-600157fefd43.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Forms > Wizard on your online demo

The problem here is the bmd-label-static class... it is added automatically. How can I control this?
In my case it appears on datetimepicker label
![image](https://user-images.githubusercontent.com/16140960/41182558-37b288ee-6b44-11e8-84e8-7f8198b4b8e9.png)

**Comment by groovemen** [comment]
Hello @israelias94 , thank you for using our products, please update your project to the latest version (**v2.1.0**) of the product where we fixed this issues. Also, check the [documentation](https://demos.creative-tim.com/material-dashboard/docs/2.0/getting-started/build-tools.html#using-input-labels-in-a-form) to see how to use the labels.

All the best,
 Stefan
