### ISSUE TITLE
Add PrivateRoute before reach the dashboard, the page is blank white

### ISSUE THREAD

**Issue by bertha22** [creativetimofficial/material-dashboard#63]
# Prerequisites

I would like to add a login page before reach the dashboard

# Expected Behavior

login page first, then the dashboard shows up.

# Current Behavior

login page shows, but the dashboard page is blank white. 

# Failure Information (for bugs)
my code is like attached

[App.txt](https://github.com/creativetimofficial/material-dashboard/files/2114413/App.txt)
[history.txt](https://github.com/creativetimofficial/material-dashboard/files/2114414/history.txt)
[PrivateRoute.txt](https://github.com/creativetimofficial/material-dashboard/files/2114415/PrivateRoute.txt)

**Comment by timcreative** [comment]
Thank you for your interest. We'll make a todo list of what we want to improve and you'll get the assignment. Stay close!

**Comment by marqbeniamin** [comment]
Thank you for your interest. We'll make a todo list of what we want to improve and you'll get the assignment. Stay close!
