### ISSUE TITLE
arrive.js missing from repo and no link

### ISSUE THREAD

**Issue by thoraxe** [creativetimofficial/material-dashboard#68]
The [starter template](https://demos.creative-tim.com/material-dashboard/docs/2.0/getting-started/introduction.html#starter-template) refers to `arrive.js`. I assume you are talking about:

https://github.com/uzairfarooq/arrive

Interestingly, the [live preview](https://demos.creative-tim.com/material-dashboard/examples/dashboard.html) doesn't use this library.

**Comment by groovemen** [comment]
Hello @thoraxe, thank you for using our products, we fixed this issue in the documentation. Thank you for your observation. All the best, Stefan
