### ISSUE TITLE
Multiple forms in wizard

### ISSUE THREAD

**Issue by Ananya-96** [creativetimofficial/material-dashboard#69]
# Prerequisites
I am currently using paid version of material dashboard which has wizard component. I want to have separate forms for each tab in the wizard. The form is getting submitted but the problem is the form is not getting validated at each tab. Only the first form is getting validated. I used .validate({}) and required="true" but of no help.
I checked that in demo.js
`initMaterialWizard: function() {
        // Code for the Validator
        var $validator = $('.wizard-card form').validate({
            rules: {
                firstname: {
                    required: true,
                    minlength: 3
                },
                lastname: {
                    required: true,
                    minlength: 3
                },
                email: {
                    required: true,
                    minlength: 3,
                }
            },

            errorPlacement: function(error, element) {
                $(element).parent('div').addClass('has-error');
            }
        });`

I found this code and the validation is done for single form.

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Multiple form validation in wizard

# Current Behavior

Validation not working. Even when the attribute is declared as required, the form gets submitted

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

I found a fix but not sure if this is the right way.

` initMaterialWizard: function(forms) {
        // Code for the Validator
       var validator = new Array()
       for(i=0;i<forms.length;i++){
        
         validator[i] = $(forms[i]).validate({
            errorPlacement: function(error, element) {
                $(element).parent('div').addClass('has-error');
            }
        });
       }`

I pass the ids of the form to init function by which i create validate function for all the forms. Let me know if there is any other way to do this or if this can be implemented.

**Comment by groovemen** [comment]
Hello @Ananya-96, thank you for using our template and also for your interest in our products and for your good observation by finding this problem. We have prezented an example of how you can handle the Wizard form, so we have created a validation example in `demo.js` file (_from line: **297**_), in wich you have to create validation for all content of the tabs that you need.

As you said, you need a form in each tab but this wizard is wraped in a `<form>`. However, our advice is to use the default structure of a Wizard Form and try to validate each input that you need in the JS file. If you want to have a form on every tab, you don't need to use a wizard. 

All the best,
Stefan

**Comment by Ananya-96** [comment]
Thank you @groovemen
