### ISSUE TITLE
Enhancement Request: add an user drop-down menu

### ISSUE THREAD

**Issue by mariusa** [creativetimofficial/material-dashboard#70]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Clicking on the user icon at top-right should show a drop-down menu, with several links:
* Profile
* Settings
* separator
* Sign out

(keep profile linking to current page, the rest don't need to work)

# Current Behavior

Icon links to a page

**Comment by groovemen** [comment]
Hello @mariusa,

Thank you for using our products, we appreciate your contribution and the intention to help us to make our product better. 

I just make a test to see how it looks:

<img width="575" alt="screen shot 2018-07-11 at 11 15 42" src="https://user-images.githubusercontent.com/21063398/42559080-c7a09448-84fb-11e8-9a8b-32b2cb92105d.png">

We'll integrate it into the next update. 
All the best, 
Stefan
