### ISSUE TITLE
Error in icons section 

### ISSUE THREAD

**Issue by DeepanshuRKM** [creativetimofficial/material-dashboard#72]
In side navigation, 
there is bug during scroll. Text and icons are going mismatch alignment.

![image](https://user-images.githubusercontent.com/39991570/41972357-4a952512-7a2f-11e8-95f8-e1b02c9e608b.png)

**Comment by marqbeniamin** [comment]
Here is an iframe with this src https://material.io/tools/icons/?style=baseline. If you check this link on a browser with a lower height, you will see the problem.

![screen shot 2018-06-27 at 16 55 02](https://user-images.githubusercontent.com/4600172/41978733-189f07ca-7a2b-11e8-98af-e17387630f98.png)
