### ISSUE TITLE
Bootstrap Collapse

### ISSUE THREAD

**Issue by eDigirolamo** [creativetimofficial/material-dashboard#78]
Bootstrap navbar collapse not working when your material-dashboard.css is included. upon removing that css file bootstrap collapsing navbar works as expected on mobile

**Comment by groovemen** [comment]
Hello @eDigirolamo, thank you for your interest in working with our products, you have to change the following files to have the style from Bootstrap: navbar.scss, sidebar-and-main-panel.scss, responsive.scss. Best, Stefan

**Comment by eDigirolamo** [comment]
Change them how?
