### ISSUE TITLE
Choppy/Laggy scroll in chrome, edge 

### ISSUE THREAD

**Issue by saeed74** [creativetimofficial/material-dashboard#79]
scrolling with mouse wheel is not smooth as normal in chrome or edge, its hardly scrolling! 
i mean, screen jumping while scroll happen with mouse.

**Comment by groovemen** [comment]
Hello @saeed74, 

Thank you for using our products and for your feedback, we will integrate into the next update the Kinetic scrolling plugin that will fix this inconvenience. 

Please let us know if we can help you with anything else.

Best, 
Stefan
