### ISSUE TITLE
Include data validation and text editor plugins

### ISSUE THREAD

**Issue by Elvis254** [creativetimofficial/material-dashboard#81]
Hi, 

I would like us to include data validation and text editor plugins.
They are a must have on the admin dashboard panels.

I would like if we could edit the `summernote js` plugin fetched from [https://summernote.org](url) css and js code to fit in with material design principles. And also edit the `jquery validation plugin js`  fetched from [https://jqueryvalidation.org](url) as suggestions. 

Please, I have used your material dashboard plugin to develop an admin panel for one of my clients and they like it. But now these two plugins are required and I don't know where to start or to go about it.

Any advice will be much appreciated.

**Comment by groovemen** [comment]
Hello @Elvis254, 

Thank you for using our products, there should be no problem in integrating a new plugin in your project. For example, in the PRO version, we are using the **jQuery Validation Plugin** and it works just fine. 
Please let us know if we can help you with anything else.

All the best, 
Stefan

**Comment by Elvis254** [comment]
How do I get the pro version? I would like to know how you use the `jQuery Validation Plugin`

**Comment by groovemen** [comment]
Hello again @Elvis254,

Here you can find the PRO version of the material dashboard: https://www.creative-tim.com/product/material-dashboard-pro 

Best,
Stefan
