### ISSUE TITLE
infinite horizontal scroll in rtl page

### ISSUE THREAD

**Issue by tuytoosh** [creativetimofficial/material-dashboard#82]
I downloaded latest version with rtl support, but there is an infinite scroll at bottom of page... how to fix it?
 
![untitled](https://user-images.githubusercontent.com/8298095/45106301-86617e80-b14b-11e8-9b2c-0cb2bf9f19e2.png)

**Comment by groovemen** [comment]
Hello @tuytoosh, 

thank you for using our products, please let us know what browser are you using because I checked on the demo version: https://demos.creative-tim.com/material-dashboard/examples/rtl.html but everything looks fine.

Best, 
Stefam

**Comment by tuytoosh** [comment]
Thanks for your response, I checked now your demo again and that issue is still there... I am using last version of chrome. when you are in top of page all thing are ok, but when you scroll down a bit, the scroll bar appears as I captured in picture.

**Comment by SajjadSM** [comment]
I have this problem too.
I see demo on latest version of chrome and firefox and this problem still there

**Comment by SajjadSM** [comment]
Finally i find the problem.
There is a unclosed element in RTL.html file.
<div class="wrapper ">

**Comment by SimaAmini** [comment]
I'm having the same problem with the angular version.

**Comment by mostafashabanelbanna** [comment]
i still having the same issue, even after i closed the div its still doing this wired behavior on scrolling.

**Comment by mostafashabanelbanna** [comment]
it was working perfctly before i updated my browser, i'm using chrome....

**Comment by groovemen** [comment]
Hello @mostafashabanelbanna,

Thank you for using our products, please let us know if the scroll behavior is presented only on the RTL page. Also, please let us know how to reproduce the issue, which OS are you using.

Best, 
Stefan

**Comment by mostafashabanelbanna** [comment]
it happens only on the RTL page, and i'm using windows...
i removed this script <script src="../assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
now it's working, but i don't know what's this will lead to?
