### ISSUE TITLE
Branding primary color not working for card headers

### ISSUE THREAD

**Issue by somlyaip-hl** [creativetimofficial/material-dashboard#84]
# Expected Behavior

When I update `$brand-primary` variable in `assets/scss/material-dashboard/variables/_brand.scss` and run `gulp compile:scss` change `.card-header-primary` css class' background too.

# Current Behavior

Links, buttons (with `.btn-primary` class), inputs, etc. are correctly modified, but `.card-header-primary` class is still purple.

# Failure Information (for bugs)

For details see above.

## Steps to Reproduce

1. `npm i material-dashboard`
2. `cd node_modules/material-dashboard`
3. Update `$brand-primary` variable in `assets/scss/material-dashboard/variables/_brand.scss` 
4.  `gulp compile:scss`
5. Test it with:
  ```html
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title">Filters</h4>
        </div>

        <div class="card-body">
            <p>Here are some filter controls..</p>
        </div>
    </div>
  ```

## Context

* Device: PC
* Operating System: Windows 10
* Browser and Version: Firefox Developer Edition 64 x64, Chrome 69

**Comment by groovemen** [comment]
Hello @somlyaip-hl, 

Thank you for using our products, you have to make the following changes to change the header of the cards: 
- go to `assets/scss/material-dashboard/_card.scss` at line: **164** and you have to change the `background: linear-gradient(60deg, $purple-400, $purple-600); ` with the colors that you want.

Hope that information helps you. Please let us know if we can help you with anything else.
All the best, 
Stefan

**Comment by somlyaip-hl** [comment]
Hello @groovemen,

It works. Thank you. Sorry for the late comment. 

Regards,
Pál
