### ISSUE TITLE
Doc description has something wrong

### ISSUE THREAD

**Issue by edwardhu** [creativetimofficial/material-dashboard#87]
The compile SCSS part of the doc has something wrong!

Compile SCSS
1. Download the project’s zip.
2. Make sure you have node.js (https://nodejs.org/en/) installed.
3. Type npm install in terminal/console in the source folder where package.json is located.
4. Run in terminal gulp open-app for opening the Dashboard Page (default) of the product. You can set in gulpfile.js from your downloaded archive any page you want to open in browser, at line 30: gulp.src('examples/dashboard.html').
5. Run in terminal gulp compile:scss for a single compilation or gulp watch for continous compilation of the changes that you make in *.scss files. This command should be run in the same folder where gulpfile.js and package.json are located.

On my Windows laptop, step 5 should be **gulp compile-scss**
I've checked the gulp file and think that the other platform should type in the same command.
Please edit it.
Thank you :-)

**Comment by groovemen** [comment]
Hello @edwardhu,

Thank you for using our products and also for letting us know about this issue, we'll have an update for this product on the next couple days and we'll also fix this issue.

Best, 
Stefan
