### ISSUE TITLE
Graph Datas Not Change. [For Material Dashboard Theme]

### ISSUE THREAD

**Issue by abdlkdrgndz** [creativetimofficial/material-dashboard#93]
Hi Creative Tim,

When I change the values ​​on the graphs, they are not reflected in the graph. I'm doing it in the demo.js file, but there's no change in the chart. How do graphic values ​​change?

This theme : https://www.creative-tim.com/product/material-dashboard

**Comment by kopi-kosong** [comment]
Hi, 

Did you manage to find out why? I had the same issue.

**Comment by groovemen** [comment]
Hello there, 

Thank you for your interest in working with our products, you can find the initialization for the chars in `assets/js/material-dashboard.js` you can search after the **initDashboardPageCharts** function() from **line 310**.
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
